stages:
  - test

test:
  stage: test
  image: python:3.7
  script:
    - apt-get update && apt-get install -y tesseract-ocr libtesseract-dev libleptonica-dev pkg-config xvfb
    - python3.7 -m venv venv
    - ./venv/bin/pip install -r requirements.txt
    - export LC_ALL=C
    - ./venv/bin/pytest
  coverage: '/\d+\%\s*$/'
  artifacts:
    paths:
      - htmlcov
    reports:
      junit: report.xml
  tags:
    - docker
